/* eslint-disable */
/**
 * Generated API stub.
 *
 * This file is auto-generated by Convex. Run `npx convex dev` to regenerate.
 */

import { anyApi } from "convex/server";

export const api = anyApi;
