/* eslint-disable */
/**
 * Generated API type definitions.
 *
 * This file is auto-generated by Convex. Run `npx convex dev` to regenerate.
 */

import type { ApiFromModules } from "convex/server";
import type * as projects from "../projects";
import type * as tasks from "../tasks";
import type * as decisions from "../decisions";
import type * as agentRuns from "../agentRuns";
import type * as activities from "../activities";
import type * as seed from "../seed";

/**
 * A utility for referencing Convex functions in your app's API.
 */
declare const fullApi: ApiFromModules<{
  projects: typeof projects;
  tasks: typeof tasks;
  decisions: typeof decisions;
  agentRuns: typeof agentRuns;
  activities: typeof activities;
  seed: typeof seed;
}>;
export declare const api: typeof fullApi;
