/* eslint-disable */
/**
 * Generated data model types.
 *
 * This file is auto-generated by Convex. Run `npx convex dev` to regenerate.
 */

import type { GenericId, GenericDocument, GenericDataModel } from "convex/server";

export type Id<TableName extends keyof DataModel["tables"]> = GenericId<TableName>;

export type DataModel = {
  tables: {
    projects: {
      _id: Id<"projects">;
      slug: string;
      name: string;
      description: string;
      status: "active" | "paused" | "archived";
      githubUrl?: string;
      color: string;
    };
    tasks: {
      _id: Id<"tasks">;
      projectSlug: string;
      title: string;
      status: "todo" | "in-progress" | "done";
      assignee?: string;
      priority: "low" | "medium" | "high";
      createdAt: number;
    };
    decisions: {
      _id: Id<"decisions">;
      projectSlug: string;
      title: string;
      context: string;
      options: string[];
      recommendation?: string;
      status: "needs-sean" | "needs-agent" | "resolved" | "deferred";
      createdAt: number;
      resolvedAt?: number;
      resolution?: string;
    };
    agentRuns: {
      _id: Id<"agentRuns">;
      agentId: string;
      projectSlug?: string;
      status: "running" | "done" | "failed";
      startedAt: number;
      endedAt?: number;
      summary?: string;
    };
    activities: {
      _id: Id<"activities">;
      projectSlug?: string;
      type: "commit" | "decision" | "task" | "agent" | "note";
      actor: string;
      message: string;
      createdAt: number;
    };
  };
};
