/* eslint-disable */
/**
 * Generated server types.
 *
 * This file is auto-generated by Convex. Run `npx convex dev` to regenerate.
 */

import type {
  GenericQueryCtx,
  GenericMutationCtx,
  GenericActionCtx,
  FunctionReference,
} from "convex/server";
import type { DataModel } from "./dataModel";

export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;

export {
  query,
  mutation,
  action,
  internalQuery,
  internalMutation,
  internalAction,
} from "convex/server";
